{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'darts'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-2-cafe4c92f5cd>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mdarts\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmodels\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mNBEATSModel\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mdarts\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mdataprocessing\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mtransformers\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mScaler\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mdarts\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmetrics\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmae\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mrmse\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mjoblib\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'darts'"
     ]
    }
   ],
   "source": [
    "from darts.models import NBEATSModel\n",
    "from darts.dataprocessing.transformers import Scaler\n",
    "from darts.metrics import mae, rmse\n",
    "import joblib\n",
    "\n",
    "#Data pipeline for model training of NBEATS forecasting. Input must be a timeseries float32.\n",
    "\n",
    "class ForecastingPipeline:\n",
    "    def __init__(self, input_chunk_length, output_chunk_length, model_params=None):\n",
    "        \"\"\"\n",
    "        Initialize forecastign pipeline.\n",
    "\n",
    "        :param input_chunk_length: size of input chunk lenght.\n",
    "        :param output_chunk_length: size of output chunk lenght.\n",
    "        :param model_params: N-BEATS model parameters.\n",
    "        \"\"\"\n",
    "        self.input_chunk_length = input_chunk_length\n",
    "        self.output_chunk_length = output_chunk_length\n",
    "        self.model_params = model_params if model_params else {}\n",
    "        self.epochs = epochs\n",
    "        self.model = None\n",
    "        self.scaler = None\n",
    "\n",
    "    def preparing_data(self, series, covariates=None):\n",
    "        \"\"\"\n",
    "        Data scaling to easy model train.\n",
    "\n",
    "        :param series: main time series (target).\n",
    "        :param covariates: Covariates (optional).\n",
    "        :return: scalaed series.\n",
    "        \"\"\"\n",
    "        self.scaler = Scaler()\n",
    "        scaled_series = self.scaler.fit_transform(series)\n",
    "        scaled_covariates = None\n",
    "        if covariates is not None:\n",
    "            scaled_covariates = self.scaler.fit_transofrm(covariates)\n",
    "        return scaled_series, scaled_covariates\n",
    "\n",
    "    def setting_modelo(self):\n",
    "        \"\"\"\n",
    "        Setting up N-Beats model with given parameters.\n",
    "        \"\"\"\n",
    "        self.model = NBEATSModel(\n",
    "            input_chunk_length=self.input_chunk_length,\n",
    "            output_chunk_length=self.output_chunk_length,\n",
    "            **self.model_params\n",
    "        )\n",
    "\n",
    "    def training_model(self, train_series, covariates=None, val_series=None, val_covariates=None):\n",
    "        \"\"\"\n",
    "        Training N-BEATS model.\n",
    "\n",
    "        :param train_series: Time series for training.\n",
    "        :param covariates: Covariates for training (optional).\n",
    "        :param val_series: Time series for validation (optional).\n",
    "        :param val_covariates: Covariates for validation (optional).\n",
    "        :param epochs: Number of epochs for training.\n",
    "        \"\"\"\n",
    "        if not self.model:\n",
    "            self.setting_model()\n",
    "        self.model.fit(\n",
    "            series=train_series,\n",
    "            past_covariates=covariates,\n",
    "            val_series=val_series,\n",
    "            val_past_covariates=val_covariates,\n",
    "            epochs=self.epochs\n",
    "        )\n",
    "\n",
    "    def model_evaluation(self, test_series, covariates=None):\n",
    "        \"\"\"\n",
    "        Model evaluation with MAE and RMSE.\n",
    "        \n",
    "        Args:\n",
    "            test_series: Real test series.\n",
    "            test_covariates: Covariates to predict, if so.\n",
    "        \n",
    "        Returns:\n",
    "            Dictionary with MAE and RMSE.\n",
    "        \"\"\"\n",
    "        if not self.model:\n",
    "            raise ValueError(\"The model needs to be trained before evaluation metrics.\")\n",
    "        \n",
    "        #Making predictions\n",
    "        preds = self.model.predict(\n",
    "            n=len(test_series),\n",
    "            past_covariates=test_covariates\n",
    "        )\n",
    "        \n",
    "        #Calculating metrics\n",
    "        mae_value = mae(test_series, preds)\n",
    "        rmse_value = rmse(test_series, preds)\n",
    "        \n",
    "        return {\n",
    "            \"MAE\": mae_value,\n",
    "            \"RMSE\": rmse_value\n",
    "        }\n",
    "    \n",
    "    def save_model(self, path):\n",
    "        \"\"\"\n",
    "        Save the model and scaler.\n",
    "        \n",
    "        :param path: path to save the model and the scaler.\n",
    "        \"\"\"\n",
    "        self.model.save_model(f\"{path}/nbeats_model.pth.tar\")\n",
    "        joblib.dump(self.scaler, f\"{path}/scaler.pkl\")  "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.6"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
